# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build
on:
  push:
    branches:
      - "*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest     
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm ci
      - name: Build turbo apps
        run: npm run build
