# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Deploy
on:
  push:
    branches:
      - "master"
env:
  NODE_VERSION: "16"
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@maste
      - name: Build the docker presence image
        run: docker build -t hacksore/presence:latest .
        working-directory: apps/bot
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}       
      - name: Push Bot image
        run: docker push hacksore/presence-bot:latest        
      - name: Deploy to firebase
        run: npm run deploy
