name: Deploy Bot
on:
  push:
    branches:
      - "master"
env:
  NODE_VERSION: "16"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Run Buildx (push image)
        run: |
          docker buildx build \
            --platform linux/arm/v7 \
            --tag hacksore/presence-bot:latest \
            --file ./Dockerfile \
            --output type=image,push=true .
